### ISSUE TITLE
Chunk: Stack overflow on 'degenerate' chunks

### ISSUE THREAD

**Issue by BardurArantsson** [zio/zio#4112]
(Apologies if this is already known, I couldn't find any reports.)

The following example fails with a StackOverflow exception:

```
var v = Chunk.single(UByte(0))
for (i <- 0 until 500000) {
  v = v :+ UByte(0)
}

Console.println("Materialize")
val m = v.materialize
```

Just prints

```
Materialize

An exception or error caused a run to abort. 
java.lang.StackOverflowError
	at zio.Chunk$AppendN.toArray(Chunk.scala:1248)
	at zio.Chunk$AppendN.toArray(Chunk.scala:1248)
	at zio.Chunk$AppendN.toArray(Chunk.scala:1248)
	at zio.Chunk$AppendN.toArray(Chunk.scala:1248)
	at zio.Chunk$AppendN.toArray(Chunk.scala:1248)
	at zio.Chunk$AppendN.toArray(Chunk.scala:1248)
	at zio.Chunk$AppendN.toArray(Chunk.scala:1248)
```

Obviously, the code is kind of pathological, but presumably it should work?

**Comment by adamgfraser** [comment]
@BardurArantsson This was resolved by #4088. Can you try on the latest snapshot? Otherwise it will be available in the next release which should be coming out shortly.

**Comment by BardurArantsson** [comment]
Oh, apologies, I missed that report in my search.

Are snapshots published as maven artifacts somewhere?

**Comment by adamgfraser** [comment]
No worries at all!. Yes. There is a link to them in the badges at the top of the read me on the Github repository.

**Comment by BardurArantsson** [comment]
Yup, after fiddling a bit getting the snapshots to resolve, it works!

**Comment by BardurArantsson** [comment]
I'm afraid I may have spoken too soon -- when working further my I discovered what I think may another similar problem.

Here's a reproducer that still fails on the snapshot (1.0.0+29-7f6dc1a0-SNAPSHOT):

```
var buf = Chunk[Byte]()
val n = 16000

def appendStringNul(bytes: Chunk[Byte]): Unit =
  buf = (buf ++ bytes) :+ 0

for (_ <- 0 until n) {
  appendStringNul(Chunk.fill[Byte](16)(0))
  appendStringNul(Chunk.fill[Byte](96)(0))
}

Console.println("Materialize")
val m = buf.materialize
Console.println("Materialize done")
```

(forgot to mention, but the UByte type is from Spire, but I don't imagine it's essential in any way.)

**Comment by adamgfraser** [comment]
@BardurArantsson Thanks! Just submitted a fix for this.
